### ISSUE TITLE
cube file precision

### ISSUE THREAD

**Issue by gtphil1** [cameramanben/LUTCalc#14]
Hi, I'm running into precision limits when converting HLG to linear (Display HLG OOTF (Normalised)). Example file attached. It looks like values are limited to 6 decimal places in cube output. This LUT outputs really tiny values, so it ends up with banding and a lot of values rounded to zero. Would it be possible to use floating point exponential notation instead? 

For context, I'm trying to work with HLG footage from the Fuji X-T3 in FCPX, and want to convert to linear space for color edits and other effects. I've tried applying this LUT and its reverse as a "no-op", and a lot of color definition is lost. 

Thanks!

[HLG_Linear.cube.txt](https://github.com/cameramanben/LUTCalc/files/5093042/HLG_Linear.cube.txt)

**Comment by cameramanben** [comment]
Hi gtphil1,

I'm just adding in a precision option in the settings - so you can set to arbitrary fixed-point decimal places,

Ben

**Comment by cameramanben** [comment]
Hi gtphil1,

sorry for my slowness - a few things meant that i had trouble pushing updates.

I've pushed some updates to a 'testing' version on the website: [LUTCalc 3.3 Beta 1](http://cameramanben.github.io/LUTCalc/testing/)

this includes 'Decimal LUT Precision' under settings - the default is 8 decimal places, but you can go as far as 128 if you are so inclined ;-)

I'll spend some time checking I haven't done anything stupid with other additions and then should have it updated soon in the main online version and Mac app.

Thanks,

Ben
