### ISSUE TITLE
Feature request: standard Rec709 and selectable nits

### ISSUE THREAD

**Issue by elonen** [cameramanben/LUTCalc#20]
If I understand correctly, currently the way to convert to/from standard Rec709 gamma is to use "Linear / Rec709", which seems to also have the linear part, not just the exponential.

What is unclear - at least to me - is what reference luminance it uses.  I.e. if I make a LUT that converts Rec709 to PQ ST2084 (10000 nits), at which nits level does it put the Rec709 max value? Rec709 reference value of 100 nits maybe? Can it be changed if to something else, e.g. if you need to convert material graded on a 120 nits display?

For clarity and precision, I think it would be useful to have a standard Rec709 gamma in the menu, with explicit peak luminance,  in addition to all the camera-custom-variants.

(In fact, maybe all the generic linears need a "peak mastering level" selector that specifies what nits value 1.0 represents, so they can be correctly mapped to absolute gammas? Not sure about this.)

**Comment by cameramanben** [comment]
Hi elonen,

sorry for the extremely slow reply, but the 'Linear / Rec709' option includes both straight linear and linear / power curve gamma options.

You should see a gamma correction box pop up under out gamma, vanilla Rec709 is the first option, and includes the linear portion in the shadows and the power curve from the crossover point, as per the spec.

LUTCalc is very much based around the scene levels (I'm a cameraman after all), and Rec709 predates the Dolby approach of absolute nits levels on displays, so in my terms the Rec709 gamma maps a nominal 90% reflectance target in the scene to 1.0 after gamma. Traditionally, my understanding is that that 1.0 is seen as 100 nits,

Ben

**Comment by cameramanben** [comment]
Hi elonen,

sorry for the extremely slow reply, but the 'Linear / Rec709' option includes both straight linear and linear / power curve gamma options.

You should see a gamma correction box pop up under out gamma, vanilla Rec709 is the first option, and includes the linear portion in the shadows and the power curve from the crossover point, as per the spec.

LUTCalc is very much based around the scene levels (I'm a cameraman after all), and Rec709 predates the Dolby approach of absolute nits levels on displays, so in my terms the Rec709 gamma maps a nominal 90% reflectance target in the scene to 1.0 after gamma. Traditionally, my understanding is that that 1.0 is seen as 100 nits,

Ben
