### ISSUE TITLE
Feature Request: ARRI LogC4 and ARRI Wide Gamut 4

### ISSUE THREAD

**Issue by CyberLykan** [cameramanben/LUTCalc#24]
See details here.
https://www.arri.com/resource/blob/278790/bea879ac0d041a925bed27a096ab3ec2/2022-05-arri-logc4-specification-data.pdf

**Comment by cameramanben** [comment]
I've just added LogC4 and ARRI Wide Gamut 4 to the master branch, and have it up on [https://lutcalc.net/testing](url)

**Comment by cameramanben** [comment]
[https://cameramanben.github.io/LUTCalc/testing/](https://cameramanben.github.io/LUTCalc/testing/) I put the link in wrong. Oops!
