### ISSUE TITLE
Load preview button doesn't load an image

### ISSUE THREAD

**Issue by jeffkirkland** [cameramanben/LUTCalc#5]
Since version 3.1 using the "load preview" button fails to load a user image. The dialog appears and you can go through the motions but nothing actually happens. This is true of both the Mac App Store version and the online version.

**Comment by cameramanben** [comment]
D'oh. Just had a chance to look through this one and I've stupidly added '.buffer' onto a function return variable which is already a buffer. Crept in with an effort to clean up the code for v3.1.

Can't believe I missed that as I often use the preview loading myself. Many thanks for letting me know.

I'll do a bit more checking to make sure nothing else is going awry and upload and close it then.

Thanks,

Ben
