### ISSUE TITLE
3D LUTs for DaVinci Resolve have the domain set incorrectly

### ISSUE THREAD

**Issue by balazer** [cameramanben/LUTCalc#7]
When LUTCalc is set to generate a 3D LUT and when LUT Type is set to DaVinci Resolve 12+ auto (.cube) or DaVinci Resolve (.cube), setting Input Scaling Max to a value other than 1.0 causes LUTCalc to write an incorrect domain keyword in the output LUT file.

The LUTCalc .cube file will contain lines like these:

> TITLE "Custom LUT"
> LUT_3D_SIZE 65
> LUT_1D_INPUT_RANGE 0 1.095
> \# S-Log3/Passthrough -> ACEScc/Passthrough, CineEI Shift -5.00, Black Level -35.84% IRE, Input 100% -> Output 100% - Created with LUTCalc v3.1.1 by Ben Turley June 2017

The `LUT_1D_INPUT_RANGE` keyword is not valid in a 3D LUT.  DaVinci Resolve will ignore that keyword.  (Tested in DaVinci Resolve 12.5)  The correct keyword is `LUT_3D_INPUT_RANGE`.

**Comment by Nick-Shaw** [comment]
`LUT_1D_INPUT_RANGE` is a valid keyword, but only if the LUT includes a 1D (shaper) LUT. Then another line such as `LUT_1D_SIZE 4096` is needed too. Resolve supports .cube files containing 3D LUTs only, 1D LUTs only, or a 1D LUT followed by a 3D LUT. Each can have a domain declared if necessary.

**Comment by cameramanben** [comment]
Oops! Surprised this one has managed to slip by for so long. Thanks for the heads up and I'll get on to the fix,

Ben

**Comment by cameramanben** [comment]
Should now be updated with the fix. Ben
